server:
  port: 8078

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
#    healthcheck:
#      enabled: true  
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
management:
  endpoint:
    health:
      show-details: always   
      
# zipkin    
spring:
  zipkin:
    base-url: http://localhost:9411
   
  sleuth:
    sampler:
      probability: 1.0
# zipkin fim          

---
spring:
  profiles: docker
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/ 