server:
  port: 8061

eureka:
  dashboard:
     enabled: true
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
#      http://${eureka.instance.hostname}:${server.port}/eureka/