server:
  port: 8080
  
# ----------------------------------------
# ACTUATOR PROPERTIES
# ----------------------------------------
endpoints:
  sensitive: false
  
  
management:  
  #security.enabled: false
  #port: 8080
  endpoints.web.exposure.include: metrics,prometheus
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  metrics.export.prometheus.enabled: true
  
#management.endpoints.web.exposure.include=metrics,prometheus
#management.endpoint.metrics.enabled=true
#management.endpoint.prometheus.enabled=true
#management.metrics.export.prometheus.enabled=true  
  

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
#    healthcheck:
#      enabled: true  
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
management:
  endpoint:
    health:
      show-details: always
    
# zipkin    
spring:
  zipkin:
    base-url: http://localhost:9411
   
  sleuth:
    sampler:
      probability: 1.0
# zipkin fim    

---
spring:
  profiles: docker
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/ 