version: '2'
services:
    config-server:
        container_name: config-server
        build:
            context: config-service/.
            dockerfile: Dockerfile
        image: config-server:latest
        expose:
            - 8088
        networks:
            - spring-cloud-network
        #volumes:
        #    - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        logging:
            driver: json-file
    discovery-service:
        container_name: discovery-service
        build:
            context: discovery-service/.
            dockerfile: Dockerfile
        image: discovery-service:latest
        entrypoint: /app/entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:8088"}}}}'
        expose:
            - 8061
        ports:
            - 8061:8061
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
        depends_on:
            - config-server
        logging:
            driver: json-file
networks:
    spring-cloud-network:
        driver: bridge
#volumes:
#    spring-cloud-config-repo:
#        external: true
